const express = require('express');
const router = express.Router();
const rateLimit = require('express-rate-limit');
const { getSharedRule } = require('../controllers/rulesController');

const viewLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 60,
  message: { message: 'Too many requests, please try again later.' },
  standardHeaders: true,
  legacyHeaders: false,
});

/**
 * @openapi
 * tags:
 *   name: Share
 *   description: Public read-only access to shared rules (no authentication required)
 */

/**
 * @openapi
 * /share/{shareToken}:
 *   get:
 *     summary: Get a publicly shared rule
 *     description: |
 *       Returns the full version history of a rule via its share token.
 *       No authentication required. Rate limited to **60 requests per 15 minutes**.
 *     tags: [Share]
 *     parameters:
 *       - in: path
 *         name: shareToken
 *         required: true
 *         schema:
 *           type: string
 *         description: The share token generated by `POST /rules/{ruleId}/share`.
 *         example: a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4
 *     responses:
 *       200:
 *         description: Shared rule with full version history.
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/SharedRule'
 *       404:
 *         description: No rule found for this share token (token invalid or share revoked).
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 *       429:
 *         description: Rate limit exceeded.
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 */
router.get('/:shareToken', viewLimiter, getSharedRule);

module.exports = router;
